---
on:
  pull_request:
    branches:
      - master
jobs:
  imports:
    name: Check Imports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: imports
          token: ${{ secrets.GITHUB_TOKEN }}
  errcheck:
    name: Check errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: errcheck
          token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    name: Check linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: lint
          token: ${{ secrets.GITHUB_TOKEN }}
  shadow:
    name: Check shadow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: shadow
          token: ${{ secrets.GITHUB_TOKEN }}
  staticcheck:
    name: Check static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: staticcheck
          token: ${{ secrets.GITHUB_TOKEN }}
  sec:
    name: Check security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: sec
          token: ${{ secrets.GITHUB_TOKEN }}
          flags: "-exclude=G104"
