---
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: "1.17"
      - name: version
        run: go version
      - name: linting
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - name: test
        run: make test
      - name: build
        run: make build
